nodeID: node1
raftAddr: 127.0.0.1:7001
httpAddr: 127.0.0.1:8001
dataDir: ./data/node1
peers:
  - {id: node1, addr: 127.0.0.1:7001}
  - {id: node2, addr: 127.0.0.1:7002}
  - {id: node3, addr: 127.0.0.1:7003}
snapshot:
  type: file
  path: ./data/node1/snapshots
  retain: 3
log:
  file: ./data/node1/raft-meta.log
  level: info
  json: true
  maxSize: 100
  maxBackups: 7
  maxAge: 30

debug:
  addr: 127.0.0.1:6061
