nodeID: node3
raftAddr: 127.0.0.3:7000
httpAddr: 127.0.0.3:8000
dataDir: ./data/node3
peers:
  - {id: node1, addr: 127.0.0.1:7000, httpAddr: 127.0.0.1:8000}
  - {id: node2, addr: 127.0.0.2:7000, httpAddr: 127.0.0.2:8000}
  - {id: node3, addr: 127.0.0.3:7000, httpAddr: 127.0.0.3:8000}
snapshot:
  type: file
  path: ./data/node3/snapshots
  retain: 3
log:
  file: ./data/node3/raft-meta.log
  level: info
  json: true
  maxSize: 100
  maxBackups: 7
  maxAge: 30

debug:
  addr: 127.0.0.3:6060
