nodeID: node3
raftAddr: 127.0.0.3:7000
httpAddr: 127.0.0.3:8000
dataDir: ./data/node3
peers:
  - {id: node1, addr: 127.0.0.1:7000, httpAddr: 127.0.0.1:8000}
  - {id: node2, addr: 127.0.0.2:7000, httpAddr: 127.0.0.2:8000}
  - {id: node3, addr: 127.0.0.3:7000, httpAddr: 127.0.0.3:8000}
snapshot:
  type: file
  retain: 3
raft:
  applyTimeout: 5s
  snapshotInterval: 10m
  snapshotThreshold: 1024
log:
  file: ./data/node3/raft-meta.log
  level: info
  json: false
  maxSize: 100MB
  maxBackups: 7
  maxAge: 30

debug:
  addr: 127.0.0.3:6060
