nodeID: node3
raftAddr: 127.0.0.1:7003
httpAddr: 127.0.0.1:8003
dataDir: ./data/node3
peers:
  - {id: node1, addr: 127.0.0.1:7001}
  - {id: node2, addr: 127.0.0.1:7002}
  - {id: node3, addr: 127.0.0.1:7003}
snapshot:
  type: file
  path: ./data/node3/snapshots
  retain: 3
log:
  file: ./data/node3/raft-meta.log
  level: info
  json: true
  maxSize: 100
  maxBackups: 7
  maxAge: 30
